ProjetCrypto/src/Entity/Cryptomonnaie.php
<?php

namespace App\Entity;

use App\Repository\CryptomonnaieRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Commentaire;
use App\Entity\Note;


/**
 * @ORM\Entity(repositoryClass=CryptomonnaieRepository::class)
 */
class Cryptomonnaie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint")
     */
    private $MarketCap;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $projet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreation;

    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="favoris")
     */
    private $fans;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="cryptomonnaie",cascade={"remove"})
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="crypto",cascade={"remove"})
     */
    private $notes;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="cryptosCreated")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;




    public function __construct()
    {
        $this->fans = new ArrayCollection();
        $this->commentaire = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarketCap(): ?int
    {
        return $this->MarketCap;
    }

    public function setMarketCap(int $MarketCap): self
    {
        $this->MarketCap = $MarketCap;

        return $this;
    }

    public function getProjet(): ?string
    {
        return $this->projet;
    }

    public function setProjet(string $projet): self
    {
        $this->projet = $projet;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

   

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFans(): Collection
    {
        return $this->fans;
    }

    public function addFan(User $fan): self
    {
        if (!$this->fans->contains($fan)) {
            $this->fans[] = $fan;
            $fan->addFavori($this);
        }

        return $this;
    }

    public function removeFan(User $fan): self
    {
        if ($this->fans->removeElement($fan)) {
            $fan->removeFavori($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire[] = $commentaire;
            $commentaire->setCryptomonnaie($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getCryptomonnaie() === $this) {
                $commentaire->setCryptomonnaie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setCrypto($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getCrypto() === $this) {
                $note->setCrypto(null);
            }
        }

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }


}

ProjetCrypto/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\Note;
use App\Entity\Commentaire;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Cryptomonnaie::class, inversedBy="fans")
     */
    private $favoris;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="user",cascade={"remove"})
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=Cryptomonnaie::class, mappedBy="creator", orphanRemoval=true)
     */
    private $cryptosCreated;


    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="user", orphanRemoval=true)
     */
    private $notes;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $pseudo;

    public function __construct()
    {
        $this->favoris = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->cryptosCreated = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Cryptomonnaie>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Cryptomonnaie $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            //$this->favoris[] += $favori;
            $this->favoris->add($favori);
        }

        return $this;
    }

    public function removeFavori(Cryptomonnaie $favori): self
    {
        $this->favoris->removeElement($favori);

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cryptomonnaie>
     */
    public function getCryptosCreated(): Collection
    {
        return $this->cryptosCreated;
    }

    public function addCryptosCreated(Cryptomonnaie $cryptosCreated): self
    {
        if (!$this->cryptosCreated->contains($cryptosCreated)) {
            $this->cryptosCreated[] = $cryptosCreated;
            $cryptosCreated->setCreator($this);
        }

        return $this;
    }

    public function removeCryptosCreated(Cryptomonnaie $cryptosCreated): self
    {
        if ($this->cryptosCreated->removeElement($cryptosCreated)) {
            // set the owning side to null (unless already changed)
            if ($cryptosCreated->getCreator() === $this) {
                $cryptosCreated->setCreator(null);
            }
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }
}

ProjetCrypto/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\Cryptomonnaie;
use App\Entity\User;
use App\Form\CryptoType;
use App\Form\FavorisType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * @Route("/{_locale}")
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }


    /**
     * @Route("/profile", name="app_profile")
     * @IsGranted("ROLE_USER")
     */
    public function profile(AuthenticationUtils $authenticationUtils, EntityManagerInterface $em): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        // Recupere l'utilisateur actuel
        $user = ($em->getRepository(User::class)->findBy(array('email' => $lastUsername)))[0];
        // Recupere les favoris de l'utilisateur actuel
        $favoris = $user->getFavoris();
        // Recupere les cryptos créées de l'utilisateur actuel
        $cryptoCreated = $user->getCryptosCreated();
        $comments = $user->getCommentaires();


        return $this->render('security/profile.html.twig', ['last_username' => $lastUsername,
            'user'=> $user,
            'favoris' => $favoris,
            'cryptoCreated'=> $cryptoCreated,
            'comments'=>$comments,
            'error' => $error]);
    }

    /**
     * ajouter une nouvelle crypto favorite.
     * Require ROLE_USER for *every* controller method in this class.
     *
     * @IsGranted("ROLE_USER")
     * @Route("/add-favoris", name="favoris.add")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    public function addFavoris(AuthenticationUtils $authenticationUtils,Request $request, EntityManagerInterface $em) : Response
    {

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        $user = $user = ($em->getRepository(User::class)->findBy(array('email' => $lastUsername)))[0];
        // Recupere les crypto
        $cryptos = $em->getRepository(Cryptomonnaie::class)->findAll();
        $options = [];
        foreach ($cryptos as $crypto){
            $options[$crypto->getName()] = $crypto;
        }

        $form = $this->createForm(FavorisType::class, ['cryptos' => $options]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
             //echo $form->get('favoris')->getData();
            $user->addFavori($form->get('favoris')->getData());
            $em->flush();
            return $this->redirectToRoute('app_profile');
        }
        return $this->render('Security/add-favoris.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * efface une crypto favorite.
     * Require ROLE_USER
     *
     * @IsGranted("ROLE_USER")
     * @Route("/delete-favoris/{id}", name="favoris.delete")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    public function deleteFavoris(Request $request, Cryptomonnaie $crypto, EntityManagerInterface $em) : Response
    {
        $form = $this->createFormBuilder()
            ->setAction($this->generateUrl('favoris.delete', ['id' => $crypto->getId()]))
            ->getForm();
        $form->handleRequest($request);
        if (!$form->isSubmitted() || !$form->isValid()) {
            return $this->render('cryptomonnaie/delete.html.twig', [
                'crypto' => $crypto,
                'form' => $form->createView(),
            ]);
        }
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $user->removeFavori($crypto);
        $em->flush();
        return $this->redirectToRoute('cryptomonnaie.list');
    }
}

ProjetCrypto/templates/security/add-favoris.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{{'Ajout favoris :'|trans}}</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">{{'Enregistrer'|trans}}</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

ProjetCrypto/templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Log in!'|trans}}{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">{{'Password'|trans}}</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        {{'Sign in'|trans}}
    </button>
</form>
{% endblock %}

ProjetCrypto/templates/security/profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<td>{{'Bienvenue'|trans}} : {{ user.pseudo }}</td>
<h2>{{'Favoris'|trans}}</h2>
<table class="table text-center">
    <tr>
        <th class="active text-center">{{'id'|trans}}</th>
        <th class="active text-center">{{'Nom'|trans}}</th>
        <th class="active text-center">{{'Sigle'|trans}}</th>
        <th class="active text-center">{{'Market cap'|trans}}</th>
        <th class="active text-center">{{'projet'|trans}}</th>
        <th class="active text-center">{{'Categorie'|trans}}</th>
        <th class="active text-center">{{'Price'|trans}}</th>
        <th class="active text-center">{{'Date creation'|trans}}</th>
        <th class="active text-center">{{'Action'|trans}}</th>
    </tr>
    {% for favori in favoris  %}
    <tr>
        <td>{{favori.id}}</td>
        <td><a href="{{ path('cryptomonnaie.show', {id: favori.id}) }}">{{favori.name}}</td>
        <td>{{favori.slug}}</td>
        <td>{{favori.marketCap}}</td>
        <td>{{favori.projet}}</td>
        <td>{{favori.categorie}}</td>
        <td>{{favori.price}}</td>
        <td>{{favori.dateCreation|date('Y-m-d')}}</td>
        <td>
            <a href="{{ path('favoris.delete', {id: favori.id}) }}"class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
        </td>

    </tr>
    {% endfor %}
</table>
<td><a href="{{ path('favoris.add')}}" class="btn btn-success">{{'Ajouter un favoris'|trans}}</a></td>

<h2>{{'Cryptomonnaie(s) créées par vous'|trans}}</h2>

<table class="table text-center">

<tr>
    <th class="active text-center">{{'id'|trans}}</th>
    <th class="active text-center">{{'Nom'|trans}}</th>
    <th class="active text-center">{{'Sigle'|trans}}</th>
    <th class="active text-center">{{'Market cap'|trans}}</th>
    <th class="active text-center">{{'projet'|trans}}</th>
    <th class="active text-center">{{'Categorie'|trans}}</th>
    <th class="active text-center">{{'Price'|trans}}</th>
    <th class="active text-center">{{'Date creation'|trans}}</th>
    <th class="active text-center">{{'Action'|trans}}</th>
</tr>
{% for crypto in cryptoCreated  %}

    <tr>
        <td>{{crypto.id}}</td>
        <td><a href="{{ path('cryptomonnaie.show', {id: crypto.id}) }}">{{crypto.name}}</td>
        <td>{{crypto.slug}}</td>
        <td>{{crypto.marketCap}}</td>
        <td>{{crypto.projet}}</td>
        <td>{{crypto.categorie}}</td>
        <td>{{crypto.price}}</td>
        <td>{{crypto.dateCreation|date('Y-m-d')}}</td>
        <td>
                    <a href="{{ path('cryptomonnaie.delete', {id: crypto.id}) }}"class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    <a href="{{ path('cryptomonnaie.edit', {id: crypto.id}) }}"class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
        </td>
    </tr>

{% endfor %}
</table>
<td><a href="{{ path('cryptomonnaie.create')}}" class="btn btn-success">{{'Créer une nouvelle crypto'|trans}}</a></td>

<h2>{{'Commentaire(s) laissés par vous'|trans}}</h2>

<table class="table text-center">
    <tr>
        <th class="active text-center">{{'Commentaire'|trans}}</th>
        <th class="active text-center">{{'Nom'|trans}}</th>
        <th class="active text-center">{{'Action'|trans}}</th>
    </tr>
    {% for com in comments  %}
    <tr>
               <td>{{com.com}}</td>
               <td><a href="{{ path('cryptomonnaie.show', {id: com.getCryptomonnaie.id}) }}">{{com.getCryptomonnaie.name}}</a></td>
               <td>
                    <a href="{{ path('commentaire.delete', {id: com.id}) }}"class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    <a href="{{ path('commentaire.edit', {id: com.id}) }}"class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
               </td>
    </tr>
{% endfor %}
</table>

{% endblock %}